title: Pramod Shanmugam Nagaraj
tagline: "Software Engineer | Full Stack Developer | AI/ML Enthusiast"
description: "Portfolio site showcasing my projects, experience, and blog posts."
url: "https://<your-username>.github.io" # or your custom domain
baseurl: ""

# Author settings
author:
  name: "Pramod Shanmugam Nagaraj"
  avatar: "/assets/img/avatar.png" # Path to your profile image
  bio: "MS in Computer Science @ Wayne State University. Building scalable AI/ML solutions."
  location: "Detroit, MI"
  email: "pramod.shanmugam@gmail.com"
  links:
    - label: "GitHub"
      icon: "fab fa-github"
      url: "https://github.com/pramodshanmugam"
    - label: "LinkedIn"
      icon: "fab fa-linkedin"
      url: "https://www.linkedin.com/in/pramod-shanmugam-nagaraj-0ba56593"
    - label: "Resume"
      icon: "fas fa-file-alt"
      url: "#"

# Theme settings
theme_mode: dark
